version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/stripe_test_task
    environment:
      STRIPE_API_KEY: "sk_test_51MaN7mCFMtaIIRBSoYqAc0Wn8HmlnK2lTGNppELKfDNiipZ1dtdQSKw8H6noKOKtU0hHGOWSabwpDqWpy5lmVE4N00tXVNqEVb"
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/home/user/postgresqldata/pgdata"
    volumes:
          - .:/home/user/postgresqldata
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
